project_id = "xzcpxatfzgusrxfreeoi"

[functions.facebook-lead-webhook]
verify_jwt = false

[functions.appointment-reminders]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false

[functions.send-reminder-email]
verify_jwt = false

[functions.send-campaign-emails]
verify_jwt = false

[functions.track-email-open]
verify_jwt = false
