// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzcpxatfzgusrxfreeoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6Y3B4YXRmemd1c3J4ZnJlZW9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA5ODUxODYsImV4cCI6MjA3NjU2MTE4Nn0.bYenWN4DbJgGZ7WCEXM8mVwI0A7XkfalJ0obi-K4TD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});